executor: cluster-generic
cluster-generic-submit-cmd: "sbatch --mem-per-cpu 4g -c {resources.cpus} -J {rule}_{wildcards} -o {log.o} -e {log.e} -t 10080"
show-failed-logs: True
printshellcmds: True
use-conda: True
verbose: False
keep-incomplete: True
keep-going: True
retries: 2
conda-prefix: "envs/instances"
notebook-listen: localhost:12500
rerun-triggers:
  - mtime
  - input

